--------------------------------------------------------
--  파일이 생성됨 - 금요일-8월-18-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ACADEMIC
--------------------------------------------------------

  CREATE TABLE "SKOTT"."ACADEMIC" 
   (	"ACADEMIC_ID" NUMBER(10,0), 
	"ACADEMIC_NAME" VARCHAR2(20 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SKOTT.ACADEMIC
SET DEFINE OFF;
Insert into SKOTT.ACADEMIC (ACADEMIC_ID,ACADEMIC_NAME) values (3,'전문대학교 졸업');
Insert into SKOTT.ACADEMIC (ACADEMIC_ID,ACADEMIC_NAME) values (4,'전문대학교 재학중');
Insert into SKOTT.ACADEMIC (ACADEMIC_ID,ACADEMIC_NAME) values (5,'고등학교 졸업');
Insert into SKOTT.ACADEMIC (ACADEMIC_ID,ACADEMIC_NAME) values (1,'4년재대학교 졸업');
Insert into SKOTT.ACADEMIC (ACADEMIC_ID,ACADEMIC_NAME) values (2,'4년재대학교 재학중');
--------------------------------------------------------
--  DDL for Index ACADEMIC_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKOTT"."ACADEMIC_PK" ON "SKOTT"."ACADEMIC" ("ACADEMIC_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger ACADEMIC_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SKOTT"."ACADEMIC_TRG" 
BEFORE INSERT ON ACADEMIC 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ACADEMIC_ID IS NULL THEN
      SELECT ACADEMIC_SEQ2.NEXTVAL INTO :NEW.ACADEMIC_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SKOTT"."ACADEMIC_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table ACADEMIC
--------------------------------------------------------

  ALTER TABLE "SKOTT"."ACADEMIC" MODIFY ("ACADEMIC_ID" NOT NULL ENABLE);
  ALTER TABLE "SKOTT"."ACADEMIC" MODIFY ("ACADEMIC_NAME" NOT NULL ENABLE);
  ALTER TABLE "SKOTT"."ACADEMIC" ADD CONSTRAINT "ACADEMIC_PK" PRIMARY KEY ("ACADEMIC_ID")
  USING INDEX "SKOTT"."ACADEMIC_PK"  ENABLE;
